### ISSUE TITLE
Can’t tell which task has exited

### ISSUE THREAD

**Issue by simonjwright** [simonjwright/cortex-gnat-rts#2]
(migrated from [Sourceforge](https://sourceforge.net/p/cortex-gnat-rts/tickets/15/)).

If a task exits, System.Tasking.Restricted.Stages.Wrapper says

    --  If we return here, the task procedure has exited (and not
    --  because of an exception, which would already have reached
    --  the last chance handler).
    raise Program_Error with "task exited, not allowed in Ravenscar”;

but it’s not at all obvious how to tell _which_ task is involved (if indeed it’s possible).

**Comment by simonjwright** [comment]
I just let the main program drop out.
```
(gdb) c
Continuing.
^C
Program received signal SIGTRAP, Trace/breakpoint trap.
__gnat_last_chance_handler (
    message=0x6848 "System.Tasking.Restricted.Stages.Wrapper: task exited, not allowed in Ravenscar", line=0)
    at /Users/simon/cortex-gnat-rts/common/last_chance_handler.c:35
35	  while (1) {}
```
The backtrace:
```
(gdb) bt
#0  __gnat_last_chance_handler (
    message=0x6848 "System.Tasking.Restricted.Stages.Wrapper: task exited, not allowed in Ravenscar", line=0)
    at /Users/simon/cortex-gnat-rts/common/last_chance_handler.c:35
#1  0x00005882 in ada.exceptions.raise_exception (e=<optimized out>, 
    message=...) at /Users/simon/cortex-gnat-rts/common/a-except.adb:38
#2  0x0000496a in system.tasking.restricted.stages.wrapper (arg1=0x200003b0)
    at /Users/simon/cortex-gnat-rts/common/gcc8/s-tarest.adb:113
...
```
Up 2, & print `P.ATCB`::
```
(gdb) p p.atcb
$1 = (access system.tasking.ada_task_control_block) 0x20000370 <environment_task.environment_tcb>
```
which makes it pretty clear which task just failed! Need to try with an ordinary task next ...
